import type { Metadata, Viewport } from "next";
import { CookiesProvider } from "next-client-cookies/server";
import { Raleway } from "next/font/google";
import AntdConfigProvider from "@context/AntdConfigProvider";
import ReactQueryProvider from "@context/ReactQueryProvider";
import "@styles/globals.scss";

import RootLayout from "./_components/RootLayout";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "My Repo Template - Frontend",
  description: "Generated by Kelscey Ortiz",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
  userScalable: false,
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable}`}>
        <AntdConfigProvider>
          <ReactQueryProvider>
            <CookiesProvider>
              <RootLayout>{children}</RootLayout>
            </CookiesProvider>
          </ReactQueryProvider>
        </AntdConfigProvider>
      </body>
    </html>
  );
}
